package casino.cashier;

import models.BetID;
import models.CardID;

import java.util.Set;

/**
 * represent a player in a casino.
 * player can own one or more playCards.
 * playCard connect to a gamingMachine to place a Bet on a game (in the current BettingRound)
 * for each Bet a unique BetID will be generated
 * tha card contains list of all generated betID's
 */
public interface IPlayerCard {
    /**
     * returns all generated betID's by this card
     *
     * @return list of betID's.
     */
    Set<BetID> returnBetIDs();

    /**
     * returns all generated betID's by this card, and clears all betID's from the card.
     *
     * @return a copied set of betID's generated by this card.
     */
    Set<BetID> returnBetIDsAndClearCard();

    /**
     * The card generates a unique betID for every bet made by the gambler on the machine.
     * A list of all generated betID’s is also stored on the card. BetID’s also contain a timestamp.
     *
     * @return a new betID
     */
    BetID generateNewBetID();

    /**
     * return number of betID's generated on this card.
     *
     * @return number of betID's
     */
    int getNumberOfBetIDs();

    /**
     * each playCard has a uniq cardID, this method will return the ID of the card
     *
     * @return the cardID
     */
    CardID getCardID();
}
